version: "3.8"

services:
  squid:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SQUID_PORT}:${SQUID_PORT}"
    environment:
      - SQUID_CACHE_DIR=/var/cache/squid
      - SQUID_PORT=3128
      - SQUID_CACHE_EXPIRY=10d
      - BANDWIDTH_LIMIT=500KB/1m
    volumes:
      - squid-cache:/var/cache/squid
      - squid-logs:/var/log/squid
      - squid-locks:/var/lock/squid
    restart: always

volumes:
  squid-cache:
  squid-logs:
  squid-locks:
